global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proxycache'
    static_configs:
      - targets: ['proxycache:8080']
    metrics_path: '/_stats'

  - job_name: 'proxycache-redis'
    static_configs:
      - targets: ['proxycache-redis:8080']
    metrics_path: '/_stats'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
