#!/usr/bin/env bash
set -euo pipefail

# Increase OS limits for high-RPS benchmarking.
#
# Usage:
#   # Best: source it so ulimit affects your shell
#   source ./increase_limits.sh
#
#   # Or run (sysctl changes apply, ulimit only affects this process):
#   ./increase_limits.sh
#
# Options:
#   --dry-run   Print commands without applying
#   --persist   Also write config files under /etc (requires sudo)

DRY_RUN=0
PERSIST=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --persist) PERSIST=1 ;;
    -h|--help)
      sed -n '1,120p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown arg: $arg" >&2
      exit 2
      ;;
  esac
done

run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "+ $*"
    return 0
  fi
  eval "$@"
}

need_sudo() {
  # If not root, prefer sudo when available.
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    command -v sudo >/dev/null 2>&1 || {
      echo "Need root or sudo for sysctl/persist steps." >&2
      exit 1
    }
    echo "sudo"
  else
    echo ""
  fi
}

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "This script currently targets Linux only." >&2
  exit 1
fi

SUDO="$(need_sudo)"

echo "== Current limits =="
echo "ulimit -n (open files): $(ulimit -n)"
echo "ulimit -u (max user procs): $(ulimit -u)"
echo

echo "== Applying ulimit for this shell/process =="
# Note: ulimit only affects current shell (or process). Source this script to affect your terminal.
run "ulimit -n 1048576 || true"
run "ulimit -u 1048576 || true"

echo
echo "== Applying sysctl runtime tuning =="

# Conservative, benchmark-friendly defaults.
# You can dial these back for production workloads.
SYSCTL_KV=(
  # accept/backlog queues
  "net.core.somaxconn=65535"
  "net.ipv4.tcp_max_syn_backlog=65535"
  "net.core.netdev_max_backlog=65535"

  # ephemeral ports (helps client/loadgen on same host)
  "net.ipv4.ip_local_port_range=10240 65535"

  # reduce TIME_WAIT pain in benchmarks
  "net.ipv4.tcp_fin_timeout=15"
  "net.ipv4.tcp_tw_reuse=1"

  # socket buffers
  "net.core.rmem_max=134217728"
  "net.core.wmem_max=134217728"
  "net.ipv4.tcp_rmem=4096 87380 134217728"
  "net.ipv4.tcp_wmem=4096 65536 134217728"

  # file handles
  "fs.file-max=2097152"
)

for kv in "${SYSCTL_KV[@]}"; do
  # shellcheck disable=SC2086
  run "${SUDO} sysctl -w ${kv}"
done

if [[ "$PERSIST" == "1" ]]; then
  echo
  echo "== Persisting sysctl + limits (requires sudo) =="

  SYSCTL_FILE="/etc/sysctl.d/99-fly-highref-benchmark.conf"
  LIMITS_FILE="/etc/security/limits.d/99-fly-highref-benchmark.conf"

  TMP_SYSCTL="$(mktemp)"
  {
    echo "# fly-highref benchmark tuning"
    echo "# generated by $(basename "$0") on $(date -Is)"
    echo
    for kv in "${SYSCTL_KV[@]}"; do
      key="${kv%%=*}"
      val="${kv#*=}"
      echo "${key} = ${val}"
    done
  } >"$TMP_SYSCTL"

  run "${SUDO} install -m 0644 \"$TMP_SYSCTL\" \"$SYSCTL_FILE\""
  run "${SUDO} sysctl --system >/dev/null"
  run "rm -f \"$TMP_SYSCTL\""

  TMP_LIMITS="$(mktemp)"
  {
    echo "# fly-highref benchmark limits"
    echo "# generated by $(basename "$0") on $(date -Is)"
    echo
    echo "* soft nofile 1048576"
    echo "* hard nofile 1048576"
    echo "* soft nproc  1048576"
    echo "* hard nproc  1048576"
  } >"$TMP_LIMITS"

  run "${SUDO} install -m 0644 \"$TMP_LIMITS\" \"$LIMITS_FILE\""
  run "rm -f \"$TMP_LIMITS\""

  echo "Wrote:"
  echo "  - $SYSCTL_FILE"
  echo "  - $LIMITS_FILE"
  echo "Note: login/session restart may be required for PAM limits to apply."
fi

echo
echo "Done."
echo "Tip: for ulimit to affect your current terminal, run:"
echo "  source ./increase_limits.sh"
