global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: fluxor
    static_configs:
      - targets: ['fluxor:8080']
    metrics_path: /metrics
